version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    overwrite: true
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 100
      runas: ec2-user
    - location: scripts/start_server.sh
      timeout: 100
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 100
      runas: ec2-user